export const apps = [
  {
    href: "/apps/gpt/app",
    title: "Structured output with GPT-4o",
    shortTitle: "GPT 4o",
    shortDesc: "Generate structured output (JSON or text) with GPT",
    tags: ["OpenAI", "GPT-4o (mini)"],
    features: [
      "Structured output generation",
      "JSON/text formatting",
      "JSON schema validation",
      "Custom prompt templates",
      "Real-time streaming",
      "Function calling support",
    ],
    useCases: [
      "Content generation",
      "Data structuring",
      "API response formatting",
      "Documentation",
      "Text analysis",
      "Format conversion",
      "Business logic",
      "Code generation",
      "Text generation",
      "Structured output generation",
    ],
    techStack: [
      "OpenAI API",
      "LangChain",
      "Zod validation",
      "Supabase storage",
      "Next.js API routes",
    ],
    image:
      "https://images.unsplash.com/photo-1553933899-131780ba04a3?q=80&w=2786&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    href: "/apps/pdf",
    title: "Chat with a PDF ",
    shortTitle: "PDF Chat",
    shortDesc: "Upload and chat with PDFs",
    tags: ["OpenAI", "GPT-4o (mini)", "PDF Processing", "Vector Search"],
    features: [
      "PDF text extraction",
      "Vector embeddings generation",
      "RAG search",
      "Semantic search",
      "Context-aware responses",
      "Document history",
    ],
    useCases: [
      "Document analysis",
      "Research assistance",
      "Legal document review",
      "Educational material study",
      "Technical documentation search",
      "Knowledge base creation",
    ],
    techStack: [
      "OpenAI Embeddings",
      "Supabase Vector Store",
      "pdf-parse",
      "LangChain",
      "Cloudflare R2",
    ],
    image:
      "https://images.unsplash.com/photo-1638787377553-0547687f3a87?q=80&w=2872&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    href: "/apps/audio/app",
    title: "Speech to text using Whisper",
    shortTitle: "Whisper",
    shortDesc: "Audio transcription & summarization",
    tags: ["Whisper", "LLaMA 3", "Audio Processing", "Transcription"],
    features: [
      "Multi-language support",
      "Real-time transcription",
      "Audio summarization",
      "Speaker diarization",
      "Timestamp generation",
      "Custom vocabulary",
    ],
    useCases: [
      "Meeting transcription",
      "Podcast processing",
      "Interview analysis",
      "Lecture notes",
      "Accessibility tools",
      "Content localization",
    ],
    techStack: [
      "Whisper API",
      "LLaMA 3",
      "Web Audio API",
      "Cloudflare R2",
      "FFmpeg",
      "Groq",
      "Replicate",
    ],
    image:
      "https://images.unsplash.com/photo-1492879291357-620e858bd26a?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    href: "/apps/vision/app",
    title: "See with GPT-4o",
    shortTitle: "GPT-4o Vision",
    shortDesc: "AI-powered image analysis",
    tags: ["OpenAI", "GPT-4o", "Computer Vision", "Image Analysis"],
    features: [
      "Multi-image analysis",
      "Detailed scene description",
      "Object detection",
      "Text extraction from images",
      "Visual question answering",
      "Image content moderation",
    ],
    useCases: [
      "Content moderation",
      "Accessibility services",
      "E-commerce product analysis",
      "Medical image interpretation",
      "Document processing",
      "Visual search systems",
    ],
    techStack: [
      "OpenAI Vision API",
      "Image processing",
      "Cloudflare R2",
      "Next.js API routes",
    ],
    image:
      "https://images.unsplash.com/photo-1696517170961-661e9dca962e?q=80&w=2960&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    href: "/apps/sdxl/app",
    title: "Images with SDXL",
    shortTitle: "SDXL",
    shortDesc: "High-quality AI image generation",
    tags: ["Replicate", "SDXL", "Image Generation", "Stable Diffusion"],
    features: [
      "Text-to-image generation",
      "High-resolution output",
      "Style customization",
      "Batch generation",
      "Image variations",
    ],
    useCases: [
      "Image generation",
      "Brand assets",
      "Social media content",
      "Presentation images",
      "Digital art creation",
      "Product visualization",
      "Marketing materials",
      "Concept art",
      "UI/UX mockups",
    ],
    techStack: [
      "Replicate API",
      "SDXL model",
      "Image processing",
      "Cloudflare R2",
    ],
    image:
      "https://images.unsplash.com/photo-1717501218385-55bc3a95be94?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    href: "/apps/dalle/app",
    title: "Images with DALL·E",
    shortTitle: "DALL·E",
    shortDesc: "AI-powered image generation",
    tags: ["OpenAI", "DALL·E 3", "Image Generation"],
    features: [
      "Text-to-image generation",
      "High-resolution output",
      "Style customization",
      "Batch generation",
      "Image variations",
    ],
    useCases: [
      "Image generation",
      "Brand assets",
      "Social media content",
      "Presentation images",
      "Digital art creation",
      "Product visualization",
      "Marketing materials",
      "Concept art",
      "UI/UX mockups",
    ],
    techStack: ["DALL·E API", "Image processing", "Cloudflare R2", "OpenAI"],
    image:
      "https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?q=80&w=2874&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    href: "/apps/llama/app",
    title: "JSON or text with LLaMA 3",
    shortTitle: "LLaMA 3",
    shortDesc: "Structured data generation with LLaMA",
    tags: ["Groq", "LLaMA 3", "JSON", "Text Generation"],
    features: [
      "Fast inference speed",
      "Structured output generation",
      "JSON/text formatting",
      "JSON schema validation",
      "Custom prompt templates",
      "Real-time streaming",
      "Function calling support",
    ],
    useCases: [
      "Content generation",
      "Data structuring",
      "API response formatting",
      "Documentation",
      "Text analysis",
      "Format conversion",
      "Business logic",
      "Code generation",
      "Text generation",
      "Structured output generation",
    ],
    techStack: ["Groq API", "LLaMA 3", "JSON processing", "Supabase"],
    image:
      "https://images.unsplash.com/photo-1674027444485-cec3da58eef4?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    href: "/apps/chat",
    title: "Advanced AI Chat Assistant",
    shortTitle: "AI Chat",
    shortDesc: "Intelligent conversational AI with advanced capabilities",
    tags: ["OpenAI", "Claude", "LLaMA 3", "Groq", "Multi-Modal"],
    features: [
      "Multiple AI model support (GPT-4, Claude 3, LLaMA 3)",
      "Multi-modal capabilities (image input)",
      "Real-time web search integration",
      "Document generation and editing",
      "Long-term conversation memory",
      "Streaming responses",
      "Tool integration",
      "Generative UI",
    ],
    useCases: [
      "Personal AI assistant",
      "Research and analysis",
      "Content creation",
      "Document processing",
      "Web search assistance",
      "Multi-modal interactions",
      "Tool-augmented conversations",
      "Knowledge base creation",
    ],
    techStack: [
      "Vercel AI SDK",
      "Multiple AI providers (OpenAI, Anthropic, Groq)",
      "Supabase Vector Store",
      "Cloudflare R2 Storage",
      "Serper API for web search",
      "Jina AI for content extraction",
      "LangChain for memory",
      "Next.js streaming",
    ],
    image:
      "https://images.unsplash.com/photo-1692607334850-4a3ede6ec657?q=80&w=3027&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    href: "/apps/claude",
    title: "JSON or text with Claude 3",
    shortTitle: "Claude 3.5 Sonnet",
    shortDesc: "AI-powered business planning",
    tags: ["Anthropic", "Claude 3", "JSON", "Business Planning"],
    features: [
      "Structured output generation",
      "JSON/text formatting",
      "JSON schema validation",
      "Custom prompt templates",
      "Real-time streaming",
      "Function calling support",
    ],
    useCases: [
      "Content generation",
      "Data structuring",
      "API response formatting",
      "Documentation",
      "Text analysis",
      "Format conversion",
      "Business logic",
      "Code generation",
      "Text generation",
      "Structured output generation",
    ],
    techStack: ["Anthropic API", "JSON Schema", "Supabase", "LangChain"],
    image:
      "https://images.unsplash.com/photo-1717501217986-f2c4842edfd7?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    href: "/apps/voice",
    title: "Text to lifelike speech",
    shortTitle: "ElevenLabs TTS",
    shortDesc: "Advanced text-to-speech synthesis",
    tags: ["Elevenlabs", "Text to Speech", "Audio Generation"],
    features: [
      "26+ languages support",
      "1000+ voice options",
      "Custom voice cloning",
      "Real-time streaming",
      "Voice emotion control",
      "Speech rate adjustment",
    ],
    useCases: [
      "Audiobook creation",
      "Video narration",
      "Accessibility tools",
      "Language learning",
      "Virtual assistants",
      "Content localization",
    ],
    techStack: [
      "ElevenLabs API",
      "Web Audio API",
      "Cloudflare R2",
      "Audio processing libraries",
    ],
    image:
      "https://images.unsplash.com/photo-1666868291591-9f8e0353c9ce?q=80&w=3027&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];
